import Head from "next/head";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Govhack 2022</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>Govhack 2022 Repo</main>
        </div>
    );
}
